exclude: '^docs/conf.py'

repos:
    # Format Code
    - repo: https://github.com/ambv/black
      rev: 21.5b2
      hooks:
        - id: black

    # Sort imports
    - repo: https://github.com/PyCQA/isort
      rev: 5.8.0
      hooks:
      - id: isort
        args: ["--profile", "black"]

    # Formatting, Whitespace, etc
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=6000']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=no']
      - id: flake8
        args: ['--ignore=E203,E501,F811,E712,W503']
