site_name: Fastaudio

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc

plugins:
  - search
  - mknotebooks

repo_name: fastaudio/fastaudio
repo_url: https://github.com/fastaudio/fastaudio
edit_uri: ""

theme:
  name: material

extra_css:
  - css/custom.css
